Try waiting up to 10 seconds for http server to come up.

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -20,6 +20,26 @@ function runIntegrationTests {
   RESULT+=$?
 }
 
+function retry {
+  cmd="$1"
+  retry_times=$2
+  retry_wait=$3
+
+  c=0
+  while [ $c -lt $((retry_times+1)) ]; do
+    c=$((c+1))
+    echo "Executing \"$cmd\", try $c"
+    $1 && return $?
+    if [ ! $c -eq $retry_times ]; then
+      echo "Command failed, will retry in $retry_wait secs"
+      sleep $retry_wait
+    else
+      echo 'Command failed, giving up.'
+      return 1
+    fi
+  done
+}
+
 # Unit tests
 runTests 'Dart' pub run test -r expanded test/dart
 runTests 'ElixirScript' $npm_bin/mocha --compilers js:babel-core/register test/elixirscript/*.js
@@ -54,6 +74,10 @@ set +e
 
 ($npm_bin/http-server -p 8000 dist) &
 server_pid=$!
+
+set -e
+retry 'curl -s -o /dev/null http://localhost:8000' 5 2
+set +e
 
 runIntegrationTests 'Dart'
 runIntegrationTests 'ElixirScript'
